### ISSUE TITLE
importGTFS() should work without a shapes.txt 

### ISSUE THREAD

**Issue by Trott** [fnogatz/transportation#4]
`shapes.txt` is an optional file. However, `importGTFS()` throws `ENOENT: no such file or directory` if it doesn't exist.

**Comment by Trott** [comment]
I'm putting together a PR that puts the logic (for not throwing an error if `shapes.txt` isn't there) into the shapes import lib rather than into `importGTFS()`. My thinking is that it's really the import libs job to know whether a file is optional or required, just like that's where one would put the logic that determines if a field is optional or required. However, a case could almost certainly be made for moving the logic to `importGTFS()` itself.

**Comment by fnogatz** [comment]
Thank you for the issue report! I endorse putting the check for the optional file into `import.shapes.js` and keep the `/import/gtfs/index.js` clean. For your PR make sure to use the latest version as I updated the code after merging your latest PR.

**Comment by Trott** [comment]
Thanks, I merged in all your changes before starting work. (Also, thanks for publishing the new version to npm.)

**Comment by fnogatz** [comment]
So after all I moved your `ENOENT` handling into `/import/gtfs/index.js` as there are more optional files and I preferred the general solution. Solved by #5, pushed and published.

**Comment by fnogatz** [comment]
Fixed a bug via `transportation@0.0.8`.
