### ISSUE TITLE
Add GTFS-RT support

### ISSUE THREAD

**Issue by kalon33** [fnogatz/transportation#46]
Would it be possible to add GTFS-RT support, in order to have real time vehicle positions, using trip-updates with actual stop times, or vehicle-positions from the GTFS-RT feed (when available)?

Thanks for implementing this :)

**Comment by fnogatz** [comment]
This project currently only uses the CSV files provided as GTFS. Since [GTFS-RT](https://developers.google.com/transit/gtfs-realtime/) uses Protocol Buffers, it will be no simple task to add realtime support. I am open for contributions which add this feature or funding to implement it :)

**Comment by kalon33** [comment]
@fnogatz Would it be easier if the feed is plain text like: 
`entity { id: "649" trip_update { trip { trip_id: "84559046-1443152" start_date: "20170630" schedule_relationship: SCHEDULED route_id: "810:A" } stop_time_update { arrival { time: 1498805400 } departure { time: 1498805400 } stop_id: "StopPoint:8738605:810:A" } stop_time_update { arrival { time: 1498805760 } departure { time: 1498805760 } stop_id: "StopPoint:8738642:810:A" } vehicle { id: "SNCF-ACCES:VehicleJourney::TNOR51_20170630:LOC" } timestamp: 1498804902 } }` ?
