### ISSUE TITLE
feature: include pickup_type from stop_times

### ISSUE THREAD

**Issue by Trott** [fnogatz/transportation#6]
Before I run off and implement something, I want to check that it fits with your ideas for the project and also make sure that you haven't already started down this path.

I'm trying to use this module for something that displays transit schedules. For my use case, it is important to have the `pickup_type` information. My data has `stop_time` entries that are `pickup_type` of `1` which means that they are drop-off only. In other words, a rider may not board the vehicle at that stop at that time. In that situation, I do not want to publish that time in the schedule because people will expect to be able to board. (Or if I do publish it, I want to include some sort of notation indicating that there is no boarding at that time.)

It seems like the raw pickup_type would be easy to add in `getStopTimes()` in `import.stop_times.js`. The only pitfall is to note that it is an optional field, so its existence needs to be checked before it is added. I see that `shape_dist_traveled` (another optional field) is already being processed this way, so it would probably just be a case of adding another `if` block similar to the one that handles `shape_dist_traveled`. Throw one in for `dropoff_type` as well as `pickup_type`, add some tests, submit PR, profit!

Does that all seem reasonable to you?

**Comment by fnogatz** [comment]
Had the same idea of generating schedules some time ago! Unfortunately I can't find the templates repo I found that time.
Your approach looks promising! I would expect to define the meanings of `0`, ..., `3` at `/lib/stop_time.js` similar to [Service.Exception](https://github.com/fnogatz/transportation/blob/abaa53dcc85c02656171afedc5cae98c5640e7d5/lib/service.js#L84) and [Service.Status](https://github.com/fnogatz/transportation/blob/abaa53dcc85c02656171afedc5cae98c5640e7d5/lib/service.js#L104).

**Comment by Trott** [comment]
OK, it's in https://github.com/fnogatz/transportation/pull/7

**Comment by fnogatz** [comment]
Merged #7, so close here.
