### ISSUE TITLE
Import fails globally if one line's arrival/departure errors

### ISSUE THREAD

**Issue by risseraka** [fnogatz/transportation#8]
In case of several-thousand-line long import files, the whole import fails if one line is not correctly formated or there're a few missing fields.

Offending line is:
https://github.com/fnogatz/transportation/blob/master/lib/import/gtfs/import.stop_times.js#L70

Is there no fault tolerance for imports?

Cheers,

**Comment by fnogatz** [comment]
Solved via #9.
